### PR TITLE
Bumps Powershell Module and Terraform Binary

### PR DESCRIPTION
**Pull request by williamayerst**
# Pull Request Template

## 📲 What

Bumps Powershell Module and Terraform Binary

## 🤔 Why

Updated Module
Terraform update required to leverage `-or-create=true` flag for `workspace select` subcommand

## 🛠 How

Standard version bump in base image

## 👀 Evidence

New TF functionality implemented via new PS module using unstable image: https://amido-dev.visualstudio.com/Amido-Stacks/_build/results?buildId=27264&view=logs&j=699f54c7-4369-57a0-4ead-e2b4c552964e&t=3c52fcce-89b7-519a-9236-286916570490&l=153

## 🕵️ How to test

Notes for QA

### CODE REVIEW

**Comment by ElvenSpellmaker** [comment]
Are there any big changes in TF between those versions?

**Comment by williamayerst** [comment]
@ElvenSpellmaker for my purposes specifically that you now have the flag to create a namespace upon selection rather than  needing to catch an error if the select fails. There are lots of updates to the TF versions, nothing backwards incompatible AFAIK and Stacks Infra is happy with it. Are you?

**Comment by ElvenSpellmaker** [comment]
> @ElvenSpellmaker for my purposes specifically that you now have the flag to create a namespace upon selection rather than needing to catch an error if the select fails. There are lots of updates to the TF versions, nothing backwards incompatible AFAIK and Stacks Infra is happy with it. Are you?

Yeah I'm happy, also my PR on independent runner automatically created the workspace for you iirc, so might need some tweaking after yours.

**Comment by williamayerst** [comment]
> > @ElvenSpellmaker
> Yeah I'm happy, also my PR on independent runner automatically created the workspace for you iirc, so might need some tweaking after yours.


The logic in the independent runner has already been changed to include the `-or-create=true` flag in a separate PR yesterday IIRC - unless you've now also just created a PR for it!

**Review by russellseymour — APPROVED** [review]
👍

**Comment by ElvenSpellmaker** [comment]
> > > @ElvenSpellmaker
> > > Yeah I'm happy, also my PR on independent runner automatically created the workspace for you iirc, so might need some tweaking after yours.
> 
> The logic in the independent runner has already been changed to include the `-or-create=true` flag in a separate PR yesterday IIRC - unless you've now also just created a PR for it!

I just made it automatically create the workspace as I can't see a point where someone doesn't want it created, similar functionality overall.

The PR can't be merged as the tests don't pass but the build does. @russellseymour said he'd look into it, not sure on the status. But the PR will need changing now anyway due to your flag PR

**Pull request merged**
